git:
  url: https://github.com/bernielomax/chicka-plugins.git
plugins:
  path: /chicka-plugins/
logging:
  path: /tmp/chicka.log
cache:
  ttl: 120
http:
  api: ":9090"
  www: ":8080"
tests:
- command: docker-images.py --threshold 50
  interval: 30
  expect: true
- command: load-average.rb --threshold 2
  interval: 10
  expect: true
- command: stringmatch.sh /tmp/test.txt dog 3
  interval: 20
  expect: true
- command: process-running.js --name foobar --inverse
  interval: 30 
  expect: true
- command: process-running.js --name chicka
  interval: 30
  expect: true
